server:
  servlet:
    # session最大超时时间(分钟)，默认为30
    session:
      timeout: 60m
  port: 80
#日志配置
logging:
  path: logback-spring.xml

spring:
  application:
    name: fgt-payment-center
  profiles:
    #默认启动模式
    active: dev
  main:
    allow-bean-definition-overriding: true
  #MVC配置
  mvc:
    view:
      prefix: "classpath:/templates/"
      suffix: ".html"
    date-format: "yyyy-MM-dd HH:mm:ss"
  #槿板配置
  thymeleaf:
    mode: "HTML5"
    cache: false
    encoding: "UTF-8"
    servlet:
      content-type: "text/html"

  # 使用druid数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      test-while-idle: false
      validation-query: SELECT 'x'
  #json配置
  jackson:
    time-zone: Asia/Chongqing
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
  # REDIS基础配置
  redis:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）毫秒
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
      # 连接超时时间（毫秒）
    timeout: 500ms
#mybaties配置
mybatis:
  mapper-locations: classpath:mapper/*/*.xml

#mapper配置
mapper:
  not-empty: false
  mappers: com.fgt.common.core.CustomerMapper

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

shiro:
  session:
    #shiro session前缀
    session-prefix: "shiro-redis-session"
    #shiro session 在redis过期时间是(分钟)
    session-time: 1800
  cache:
    #shiro缓存前缀
    cache-prefix: "shiro-redis-cache"
    #shiro缓存在redis过期时间是(分钟)
    cache-time: 180
