#开发环境
spring:
  profiles: dev
  datasource:
    name: fgt_payment_center
    username: root
    password:
    url: jdbc:mysql://localhost:3306/fgt_payment_center?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

server:
  port: 8000